const ACCOUNT_NUMBER_PATTERN = /^[0-9]{1,17}$/;
const ALPHANUMERIC_PATTERN = /^[A-Za-z0-9]*$/;
const CHARACTERS_ONLY_PATTERN = /^[a-zA-Z]*$/;
const DATE_PATTERN = /^(0[1-9]|1[0-2])\/(0[1-9]|1\d|2\d|3[01])\/\d{4}$/;
const DRIVERS_LICENSE_PATTERN = /^[A-Za-z0-9-]*$/;
const MONTH_YEAR_PATTERN = /^(0[1-9]|1[0-2])\/\d{4}$/;
const NUMERIC_PATTERN = /^[0-9]*$/;
const PHONE_NUMBER_PATTERN = /^\(?([0-9]{3})\)?[-]?([0-9]{3})[-]?([0-9]{4})$/;
const ROUTING_NUMBER_PATTERN = /^[0-9]{9}$/;
const POSTAL_CODE_PATTERN = /^[0-9]{5}$/;
const SIMPLE_EMAIL_PATTERN = /^.+@.+\..+$/;
const SSN_PATTERN = /^[0-9]{3}\-?[0-9]{2}\-?[0-9]{4}$/;
const CURRENCY_PATTERN = /^[0-9]*\.?[0-9]{0,2}$/;
const CURRENCY_ALLOW_NEGATIVE_PATTERN = /^\-?[0-9]*\.?[0-9]{0,2}$/;

export {
  ACCOUNT_NUMBER_PATTERN,
  ALPHANUMERIC_PATTERN,
  CHARACTERS_ONLY_PATTERN,
  DATE_PATTERN,
  DRIVERS_LICENSE_PATTERN,
  MONTH_YEAR_PATTERN,
  NUMERIC_PATTERN,
  PHONE_NUMBER_PATTERN,
  POSTAL_CODE_PATTERN,
  ROUTING_NUMBER_PATTERN,
  SIMPLE_EMAIL_PATTERN,
  SSN_PATTERN,
  CURRENCY_PATTERN,
  CURRENCY_ALLOW_NEGATIVE_PATTERN
};
